INCLUDE "hardware.inc"
INCLUDE "game.inc"

SECTION "Header", ROM0[$100]
    jp EntryPoint

    ds $150 - @, 0; make room for header

EntryPoint:
;do not turn off LCD outside VBlank
WaitVBlank:
ld a, [rLY]
cp 144
jp c, WaitVBlank

;turn LCD off
ld a, 0
ld [rLCDC], a

;copy tile data
ld de, Tiles
ld hl, $9000
ld bc, TilesEnd - Tiles
call Memcopy

;copy tilemap
ld de, Tilemap
ld hl, $9800
ld bc, TilemapEnd - Tilemap
call Memcopy

ld a, 0
ld b, 160
ld hl, _OAMRAM
ClearOam:
ld [hli], a
dec b
jp nz, ClearOam

;set object attributes
ld hl, _OAMRAM
ld a, 128 + 16
ld [hli], a
ld a, 16 + 8
ld [hli], a
ld a, 0
ld [hli], a
ld [hl], a



;Draw a card
ld a, $01
ld hl, HAND_CARD_1
call DrawCard
ld a, $00
ld hl, HAND_CARD_3
call DrawCard

;turn lcd on
ld a, LCDCF_ON | LCDCF_BGON | LCDCF_OBJON
ld [rLCDC], a

;during first blank frame, initialize display registers
ld a, %11100100
ld [rBGP], a
ld a, %11100100
ld [rOBP0], a

;initialize global variables
ld a, 0
ld [wFrameCounter], a
ld [wCurKeys], a
ld [wNewKeys], a
ld [wScratchA], a
ld [wScratchB], a
ld a, TL_GRS
ld [wSelectedTileIndex], a

call InitializeRandom

Main:
;wait till its not Vblank
ld a, [rLY]
cp a, 144
jp nc, Main
WaitVBlank2:
ld a, [rLY]
cp 144
jp c, WaitVBlank2

call UpdateKeys

CheckA:
    ld a, [wCurKeys]
    and a, PADF_A
    jp z, CheckLeft   
    ld a, 50
    ld b, 43
    call RandomRange8



CheckLeft:
ld a, [wCurKeys]
and a, PADF_LEFT
jp z, CheckRight

Left:
ld a, [_OAMRAM + 1]
dec a
;dont move past edge
cp a, [hl]
jp z, Main
ld [_OAMRAM + 1], a
jp Main

CheckRight:
ld a, [wCurKeys]
and a, PADF_RIGHT
jp z, Main

Right:
ld a, [_OAMRAM + 1]
inc a
cp a, 105
jp z, Main
ld [_OAMRAM + 1], a
jp Main

InitializeRandom:   
    GetTimer: 
    ld a, [$FF04] ;ff05 is timer register
    add 0
    jp z, GetTimer
    ld [wRandom], a
    ld [wRandom + 1], a
    call Random
    ret
UpdateKeys:
    ; Poll half the controller
    ld a, P1F_GET_BTN
    call .onenibble
    ld b, a ; B7-4 = 1; B3-0 = unpressed buttons

    ; Poll the other half
    ld a, P1F_GET_DPAD
    call .onenibble
    swap a ; A3-0 = unpressed directions; A7-4 = 1
    xor a, b ; A = pressed buttons + directions
    ld b, a ; B = pressed buttons + directions

    ; And release the controller
    ld a, P1F_GET_NONE
    ldh [rP1], a

    ; Combine with previous wCurKeys to make wNewKeys
    ld a, [wCurKeys]
    xor a, b ; A = keys that changed state
    and a, b ; A = keys that changed to pressed
    ld [wNewKeys], a
    ld a, b
    ld [wCurKeys], a
    ret

.onenibble
    ldh [rP1], a ; switch the key matrix
    call .knownret ; burn 10 cycles calling a known ret
    ldh a, [rP1] ; ignore value while waiting for the key matrix to settle
    ldh a, [rP1]
    ldh a, [rP1] ; this read counts
    or a, $F0 ; A7-4 = 1; A3-0 = unpressed keys
.knownret
    ret

SECTION "Tile Data", rom0
Tiles:    
    ;card tiles
    Ranks:
    ;rank 1
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ;rank 2
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ;rank 3
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ;rank 4
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ;rank 5
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ;rank 6
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ;rank 7
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ;rank 8
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ;rank 9
    DB $00,$7F,$00,$80,$1C,$9C,$14,$94
    DB $1C,$9C,$04,$84,$04,$84,$00,$80
    ; rank 10
    DB $00,$7F,$00,$80,$2E,$AE,$2A,$AA
    DB $2A,$AA,$2A,$AA,$2E,$AE,$00,$80
    TopArt:
    ; card top
    DB $00,$FF,$00,$00,$00,$00,$00,$00
    DB $00,$00,$00,$00,$00,$00,$00,$00
    Suits:
    ;suit 0
    DB $00,$FE,$10,$11,$38,$39,$7C,$7D
    DB $7C,$7D,$38,$39,$54,$55,$38,$39
    ;suit 1
    DB $00,$FE,$00,$01,$7C,$7D,$C2,$FF
    DB $82,$87,$64,$6D,$38,$39,$10,$11    
    LeftArt:
    ;left side
    DB $00,$80,$00,$80,$00,$80,$00,$80
    DB $00,$80,$00,$80,$00,$80,$00,$80  
    MiddleArt:
    ; empty middle art
    DB $00,$00,$00,$00,$00,$00,$00,$00
    DB $00,$00,$00,$00,$00,$00,$00,$00
    ;middle art 1
    DB $00,$00,$00,$10,$00,$BA,$00,$7C
    DB $10,$54,$38,$38,$38,$38,$00,$38    
    ; middle art 2
    DB $42,$84,$11,$22,$08,$11,$04,$48
    DB $00,$24,$00,$10,$01,$4A,$00,$21 
    RightArt:
    ;card right side
    DB $00,$01,$00,$01,$00,$01,$00,$01
    DB $00,$01,$00,$01,$00,$01,$00,$01 
    BottomLeft:   
    ;card bottom left corner
    DB $00,$80,$00,$80,$00,$80,$00,$80
    DB $00,$80,$00,$80,$00,$80,$00,$7F  
    Bottom:
    ;card bottom
    DB $00,$00,$00,$00,$00,$00,$00,$00
    DB $00,$00,$00,$00,$00,$00,$00,$FF
    BottomRight:
    ;card bottom right corner
    DB $00,$01,$00,$01,$00,$01,$00,$01
    DB $00,$01,$00,$01,$00,$01,$00,$FE
    
    
TilesEnd:


Tilemap:
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 
db BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, BLANK_TILE, 

TilemapEnd:


    